### ISSUE TITLE
Error when server is idle.  Too many max-spawns?

### ISSUE THREAD

**Issue by sleeps5** [Nukkit-coders/mob-plugin#50]
### Issue Description

Errors show up while server is idle.

### Steps to Reproduce the Issue

1. Walk away from the server with no one signing in
2. Watch the red errors start showing up
3. Force stop the server and restart
4. Sign into the server and enjoy the plugin again.

### OS and Versions
* Nukkit Version: 1.0dev 
* Git Commit Abbrev: 3124bc2
* Java Version: 
```
Java HotSpot(TM) 64-Bit Server VM (1.8.0_151-b12)
```
* Host Configuration: 
| Item | Value |
|:----:|:-----:|
| Host OS | Ubuntu [17.10] |  
| Memory(RAM) | 7.8 GB | 
| Storage Size | 1.1 TB | 
| Storage Type | WDC_WD5000AVVS-63M8B0 Corsair_Nova_2_SSD Unknown  | 
| CPU Type | AMD FX(tm)-4300 Quad-Core Processor | 
| CPU Core Count | 2 cores 4 threads | 
| Upstream Bandwidth | ?? | 

* Client Configuration: 

| Item | Value |
|:----:|:-----:|
| Client Edition | ?? | 
| Client Version | ?? | 

#### Config.yml
entities:
  mob-ai: true
  auto-spawn-tick: 300
  worlds-spawn-disabled: "exampleworld"

max-spawns:
  bat: 0
  blaze: 0
  chicken: 1
  cow: 2
  creeper: 1
  enderman: 0
  ghast: 0
  husk: 0
  horse: 1
  mooshroom: 1
  ocelot: 1
  pig: 1
  polarbear: 1
  rabbit: 1
  stray: 0 
  sheep: 2
  skeleton: 1
  spider: 1
  wolf: 1
  zombie: 1

### Crashdump, Backtrace or Other Files
2018-2-10 10:30:35 [INFO] Loading nukkit.yml...
2018-2-10 10:30:35 [INFO] Loading server properties...
2018-2-10 10:30:35 [INFO] Selected English (eng) as the base language
2018-2-10 10:30:35 [INFO] Starting Minecraft: PE server version v1.2.10
2018-2-10 10:30:35 [INFO] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
2018-2-10 10:30:35 [INFO] Opening server on *:25565
2018-2-10 10:30:35 [INFO] This server is running Nukkit version 1.0dev "蘋果(Apple)派(Pie)" (API 1.0.5)
2018-2-10 10:30:35 [INFO] Nukkit is distributed under the LGPL License
2018-2-10 10:30:36 [INFO] Loading recipes...
2018-2-10 10:30:36 [INFO] Loaded 954 recipes.
2018-2-10 10:30:36 [INFO] Successfully loaded 0 resource packs
2018-2-10 10:30:36 [INFO] Loading MobPlugin v1.0
2018-2-10 10:30:36 [INFO] Enabling MobPlugin v1.0
2018-2-10 10:30:36 [INFO] [MobPlugin] Plugin enabled successful [aiEnabled:true] [autoSpawnTick:300]
2018-2-10 10:30:36 [INFO] Epoll is available. EpollEventLoop will be used.
2018-2-10 10:30:36 [INFO] Preparing level "world"
2018-2-10 10:30:36 [INFO] Starting GS4 status listener
2018-2-10 10:30:36 [INFO] Setting query port to 25565
2018-2-10 10:30:36 [INFO] Query is running on 0.0.0.0:25565
2018-2-10 10:30:36 [INFO] Default game type: Survival Mode
2018-2-10 10:30:36 [INFO] Done (1.119s)! For help, type "help" or "?"
2018-2-10 15:16:01 [INFO] THISGUY[/XXX.XXX.XXX.XXX:34215] logged in with entity id 1 at (world, 156.3049, 71.0, 104.7802)
2018-2-10 15:16:02 [INFO] THISGUY joined the game
2018-2-10 15:57:04 [INFO] THISGUY left the game
2018-2-10 15:57:04 [INFO] THISGUY[/XXX.XXX.XXX.XXX:34215] logged out due to client disconnect
2018-2-10 17:47:51 [EMERGENCY] --------- Server stopped responding --------- (64.216s)
2018-2-10 17:47:51 [EMERGENCY] Please report this to nukkit:
2018-2-10 17:47:51 [EMERGENCY]  - https://github.com/NukkitX/Nukkit/issues/new
2018-2-10 17:47:51 [EMERGENCY] ---------------- Main thread ----------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: main
2018-2-10 17:47:51 [EMERGENCY] 	PID: 1 | Suspended: false | Native: false | State: RUNNABLE
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.getBlocksAround(BaseEntity.java:208)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.checkBlockCollision(BaseEntity.java:224)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.entityBaseTick(BaseEntity.java:279)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.monster.WalkingMonster.entityBaseTick(WalkingMonster.java:182)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:162)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.level.Level.doTick(Level.java:754)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.checkTickUpdates(Server.java:989)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.tick(Server.java:1075)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.tickProcessor(Server.java:838)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.start(Server.java:815)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.<init>(Server.java:498)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Nukkit.main(Nukkit.java:102)
2018-2-10 17:47:51 [EMERGENCY] ---------------- All threads ----------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: threadDeathWatcher-3-1
2018-2-10 17:47:51 [EMERGENCY] 	PID: 81 | Suspended: false | Native: false | State: TIMED_WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.sleep(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:150)
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Nukkit Asynchronous Task Handler #4
2018-2-10 17:47:51 [EMERGENCY] 	PID: 24 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		sun.misc.Unsafe.park(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Nukkit Asynchronous Task Handler #3
2018-2-10 17:47:51 [EMERGENCY] 	PID: 23 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		sun.misc.Unsafe.park(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Nukkit Asynchronous Task Handler #2
2018-2-10 17:47:51 [EMERGENCY] 	PID: 22 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		sun.misc.Unsafe.park(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Nukkit Asynchronous Task Handler #1
2018-2-10 17:47:51 [EMERGENCY] 	PID: 21 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		sun.misc.Unsafe.park(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Nukkit Asynchronous Task Handler #0
2018-2-10 17:47:51 [EMERGENCY] 	PID: 20 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		sun.misc.Unsafe.park(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:458)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.SynchronousQueue.take(SynchronousQueue.java:924)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
2018-2-10 17:47:51 [EMERGENCY] 		java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Thread-6
2018-2-10 17:47:51 [EMERGENCY] 	PID: 19 | Suspended: false | Native: false | State: RUNNABLE
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		sun.management.ThreadImpl.dumpThreads0(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.utils.Watchdog.run(Watchdog.java:44)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: epollEventLoopGroup-2-1
2018-2-10 17:47:51 [EMERGENCY] 	PID: 18 | Suspended: false | Native: true | State: RUNNABLE
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.channel.epoll.Native.epollWait0(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.channel.epoll.Native.epollWait(Native.java:117)
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.channel.epoll.EpollEventLoop.epollWait(EpollEventLoop.java:231)
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
2018-2-10 17:47:51 [EMERGENCY] 		io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: RakNet Thread #15
2018-2-10 17:47:51 [EMERGENCY] 	PID: 15 | Suspended: false | Native: false | State: TIMED_WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.sleep(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.raknet.server.SessionManager.tickProcessor(SessionManager.java:96)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.raknet.server.SessionManager.run(SessionManager.java:70)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.raknet.server.SessionManager.<init>(SessionManager.java:58)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.raknet.server.RakNetServer.run(RakNetServer.java:101)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Console
2018-2-10 17:47:51 [EMERGENCY] 	PID: 10 | Suspended: false | Native: true | State: RUNNABLE
2018-2-10 17:47:51 [EMERGENCY] 	Thread is waiting on monitor(s):
2018-2-10 17:47:51 [EMERGENCY] 		Locked on:jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
2018-2-10 17:47:51 [EMERGENCY] 		Locked on:jline.internal.InputStreamReader.read(InputStreamReader.java:257)
2018-2-10 17:47:51 [EMERGENCY] 		Locked on:jline.internal.InputStreamReader.read(InputStreamReader.java:194)
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		java.io.FileInputStream.read0(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.io.FileInputStream.read(FileInputStream.java:207)
2018-2-10 17:47:51 [EMERGENCY] 		jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166)
2018-2-10 17:47:51 [EMERGENCY] 		jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135)
2018-2-10 17:47:51 [EMERGENCY] 		jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243)
2018-2-10 17:47:51 [EMERGENCY] 		jline.internal.InputStreamReader.read(InputStreamReader.java:257)
2018-2-10 17:47:51 [EMERGENCY] 		jline.internal.InputStreamReader.read(InputStreamReader.java:194)
2018-2-10 17:47:51 [EMERGENCY] 		jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2143)
2018-2-10 17:47:51 [EMERGENCY] 		jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2133)
2018-2-10 17:47:51 [EMERGENCY] 		jline.console.ConsoleReader.readBinding(ConsoleReader.java:2218)
2018-2-10 17:47:51 [EMERGENCY] 		jline.console.ConsoleReader.readLine(ConsoleReader.java:2459)
2018-2-10 17:47:51 [EMERGENCY] 		jline.console.ConsoleReader.readLine(ConsoleReader.java:2370)
2018-2-10 17:47:51 [EMERGENCY] 		jline.console.ConsoleReader.readLine(ConsoleReader.java:2358)
2018-2-10 17:47:51 [EMERGENCY] 		jline.console.ConsoleReader.readLine(ConsoleReader.java:2346)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.command.CommandReader.run(CommandReader.java:63)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: NonBlockingInputStreamThread
2018-2-10 17:47:51 [EMERGENCY] 	PID: 14 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Object.wait(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.run(Thread.java:748)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Thread-0
2018-2-10 17:47:51 [EMERGENCY] 	PID: 9 | Suspended: false | Native: false | State: TIMED_WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Thread.sleep(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:233)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.utils.MainLogger.run(MainLogger.java:222)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Signal Dispatcher
2018-2-10 17:47:51 [EMERGENCY] 	PID: 4 | Suspended: false | Native: false | State: RUNNABLE
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Finalizer
2018-2-10 17:47:51 [EMERGENCY] 	PID: 3 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Object.wait(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: Reference Handler
2018-2-10 17:47:51 [EMERGENCY] 	PID: 2 | Suspended: false | Native: false | State: WAITING
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Object.wait(Native Method)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.Object.wait(Object.java:502)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.ref.Reference.tryHandlePending(Reference.java:191)
2018-2-10 17:47:51 [EMERGENCY] 		java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
2018-2-10 17:47:51 [EMERGENCY] ------------------------------
2018-2-10 17:47:51 [EMERGENCY] Current Thread: main
2018-2-10 17:47:51 [EMERGENCY] 	PID: 1 | Suspended: false | Native: false | State: RUNNABLE
2018-2-10 17:47:51 [EMERGENCY] 	Stack:
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.getBlocksAround(BaseEntity.java:209)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.checkBlockCollision(BaseEntity.java:224)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.BaseEntity.entityBaseTick(BaseEntity.java:279)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.monster.WalkingMonster.entityBaseTick(WalkingMonster.java:182)
2018-2-10 17:47:51 [EMERGENCY] 		de.kniffo80.mobplugin.entities.monster.WalkingMonster.onUpdate(WalkingMonster.java:162)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.level.Level.doTick(Level.java:754)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.checkTickUpdates(Server.java:989)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.tick(Server.java:1075)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.tickProcessor(Server.java:838)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.start(Server.java:815)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Server.<init>(Server.java:498)
2018-2-10 17:47:51 [EMERGENCY] 		cn.nukkit.Nukkit.main(Nukkit.java:102)
2018-2-10 17:47:51 [EMERGENCY] ---------------------------------------------
2018-2-10 21:30:55 [EMERGENCY] RakNet crashed!

**Comment by sleeps5** [comment]
I have my cow and sheep set to 2.  I'll change them to 1 and see if that stops the issue.  I'll update tomorrow morning.

**Comment by augesrob** [comment]
Same issue i had.

**Comment by sleeps5** [comment]
It's run for about 10 hours and no errors.  Only change was moving cow and sheep from 2 to 1 on the config.yml file.  Since I don't read the directions, I didn't notice the suggested configuration (1 or 0).  Is the 1 or 0 setting boolean, not max allowable spawns per tick?

**Comment by sleeps5** [comment]
still occurs.  not able to decipher what triggers it.

**Comment by NycuRO** [comment]
This issue is by no memory available. This uses Runner, not Task, so consume 100000000gb ram. 

Good luck.

One point: Port Runner to Delayed Task with period of Thread.sleep existent and is fixed.

**Comment by LagHD** [comment]
@NycuRO You should create a PR for that, it'll help them xD

**Comment by PetteriM1** [comment]
Maybe fixed in last commit, reopen this if still hapens

**Comment by NycuRO** [comment]
@PetteriM1 Bug is happened because you cast Objects in AsyncTask or asyncronised task. Just replace AsyncTasks with Task and make them unasyncronised.

**Comment by PetteriM1** [comment]
@NycuRO You still get there crashs? I don't get these anymore

**Comment by NycuRO** [comment]
I don't test but i'm sure why it's that issue.

**Comment by NycuRO** [comment]
https://github.com/Nukkit-coders/mob-plugin/blob/MobPlugin/src/main/java/de/kniffo80/mobplugin/AutoSpawnTask.java You use runnable for AutoSpawnTask! That's the issue! Change with Task! and addat them don't be async!

**Comment by NycuRO** [comment]
I can do for you.

**Comment by NycuRO** [comment]
It's by Runnables on Objects. You can't cast Objects on Runnable/AsyncTasks because NukkitX don't support iterate maps override others. If it's happened, disable AutoSpawnTask or idk.
